org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableResourceOptimizations=false
android.enableArtProfile=false
android.experimental.enableArtProfile=false
android.versionControlInfoEnabled=false
kotlin.code.style=official
