# -*- coding: utf-8 -*-
"""把 ui_strings.txt 第 701..1100 行（1-indexed，去掉频率列）的中文串，按顺序映射为下面的英文。
按顺序对齐，避免手抖写错 key。"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
# 读取源串（按文件顺序，去掉频率列）
src = []
for line in open(os.path.join(HERE, 'ui_strings.txt'), encoding='utf-8').read().splitlines():
    line = line.strip()
    if not line:
        continue
    t = line.split('\t', 1)[1] if '\t' in line else line
    src.append(t)

EN = [
"Device Info","Create Branch","Processing…","Export SKILL.md","Chat Preview","Testing…","Import Document",
"Bot Integration","Provider Overview","Documents open and view directly in-app, no third-party office software needed.",
"Repository","Use the phone's native SpeechRecognizer, offline-capable, works out of the box",
"✅ Device architecture arm64-v8a, supports on-device offline recognition engine.",
"Background Auto-start","What do you want to ask the user?",
"Manage local models: load, unload, infer, view status, etc. Supports MNN, llama.cpp, LiteRT and other inference engines.",
"No module runtime record yet (real-time status shows here after deploying a module).",
"📄 Generate real Office files (docx/xlsx/pptx/pdf), self-built zero-dependency, generated in background for download/share.",
"\"Mini-program (native engine)\" panel (let the AI generate WXML/WXSS/JS projects with the miniapp_sdk tool).",
"● Activated (resident in memory, reused across chat turns)",
"③ Directly select a single .gguf file (simplest, recommended). The model is fully copied to the app's private directory and runs completely offline.",
"The document rendering engine is bundled (mammoth.js / SheetJS / pdf.js), opens even offline.",
"Try describing specific colors, layout, features","3D Model",
"Phone runs Sherpa-NCNN streaming model offline, from 22MB, low latency, auto sentence-break after speaking",
"FTP server started","Requires root / Shizuku to execute the local ADB shell","Video Playback","No skill selected",
"Generated","Health and Fitness","Files and Documents","Function Permission Guide",
"📦 List all AI tools provided by \"script packages (ToolPkg)\" under the workspace packages/ directory.",
"Each trigger creates an independent session, not polluting the current / history chats.",
"Wireless ADB enabled","Log in with OAuth device flow",
"GPU offload layers n_gpu_layers (default 0 = pure CPU)",
"Generating dependencies requires BouncyCastle, may be unavailable on some devices; if it fails use \"Import keystore\" (generate with keytool on PC then import).",
"No document URI","No persona card yet.","Export Artifact","Enable Local MCP Server",
"Import failed: content is not a valid SKILL.md / skill JSON / tool spec JSON",
"Try another keyword, or search for AI tool names contributed by plugins.",
"No keystore selected yet (takes effect after generate or import).","Thinking Process","In-app Verification",
"Login denied by user","Body copied","Click to start editing...","Configure Visual Dialog","HTML Content Description",
"Zorv Build Console","Feature Switch","Role Setting (system prompt core)","Exquisite Details",
"Tap to preview layout in-app","GenUI · Generative UI Chat","Enable Notification",
"Requires clicking the link to view the answer","Preparing...","Third-party App Package Name","Workspace Name",
"GitHub Mirror (switch when official is unreachable)",
"Security note: the service binds only the loopback address; no external network request can reach it. Tool calls reuse the app's same",
"Below you can manually add apps, view discovered app capabilities, and manually start or rebind.",
"Export","Built-in","Token (optional, Bearer)","(No toolkit yet)","Preview layout in chat",
"Cannot read the selected file, import failed",
"Terminal custom keybinding manager: save/query/delete/reset key→action mappings, persisted in the app's private directory for the terminal to load.",
"Allow (allow all, no more asking)","File does not exist, please save first",
"All-purpose AI assistant, rational, efficient, warm, at your service anytime.",
"List MCP Servers","Compile and Install","Please select the render channel","Script name…","Bookmark",
"Edit locally with Apache POI","Download APK Manually",
"The operation below doesn't work; please report this along with the QuroApplication / QuroPluginHost errors in logcat.",
"(No action)","Office documents (docx/xlsx/pptx): tap \"Open Preview\" top-right to view and edit text in-app. After editing, the RAG index is rebuilt automatically.",
"Import from Link","Create Scheduled Task","List Directory Contents","Token generated successfully","Mermaid Source",
"Package Management","Load","Alias and address are required","Voice Settings","Allow Custom Input",
"Plugin runtime not ready, please wait…","Alarms and Reminders","Max Retry Count",
"Read the text file content at the specified relative path in the ZorvAI workspace (QuroWorkspace) and return the full text.",
"Orchestrate a group of terminal commands by dependency (DAG): no-dependency run in parallel, upstream stdout as downstream input, any failure aborts the rest.",
"Running","Download Developer Docs","Logging in…","Installed Version","Current Workspace","Please enter...",
"Cleanup","GenUI SDK / A2UI / Markdown / HTML —— generation starts once selected",
"Initiate Authorization","Login denied or cancelled",
"After selecting a type, a blank document is created and you enter the editor.",
"Authorize this app with your GitHub account. Both methods truly log into official GitHub.",
"Select Real-time Model","Select .gguf file (recommended)","Execute Shell Command","Edit Content","Import JSON",
"Enter a third-party app package name; the system generates an ACI Token for authentication.",
"Import skill from SKILL.md / JSON / tool spec","Default App","Example: my private service","Privilege",
"Confirm Cleanup","Read File Content","Failure Threshold (circuit breaker)","Environment Not Ready",
"🎙 Supports Speech Transcription","Run","Import File","CMSv2 Module","Frequency","Kyoto Itinerary Planning",
"⚠️ mermaid node missing source (chart source)","Clearing…",
"Are you sure you want to perform this operation?","Use Custom Signature",
"AI-driven web crawler (uses the app's built-in browser WebView to render and scrape page by page).",
"Remind user to enable Accessibility Service","Exact Alarm","Example: 1080","Export Module","Display Name",
"GenUI Generative Canvas","No avatar set (shows first letter of name)",
"Multi-engine web search aggregation (unified entry): supports duckduckgo (default, free no key), tavily (configure an API Key named tavily in auth_service first, type=apikey).",
"Audit Log (God's-eye view)","Amu","Call","No Web App yet. Tap \"New Example\" or \"Import HTML\", or let the AI create one with the miniapp tool (preview right in the chat).",
"WeChat iLink connects directly to ilinkai.weixin.qq.com via phone-side HTTP long polling, no public endpoint needed.",
"New Example","No Client ID? Create one at github.com/settings/developers → New OAuth App (no callback URL needed), then paste the Client ID here.",
"Currently using the built-in debug.keystore (android/android/androiddebugkey).","Digital Human",
"Call a tool exposed by an external MCP server, letting the AI use other MCP services' capabilities.",
"ACT associated launch (underlying protocol ACI, Agent Capability Interface) is a local Root-free AIDL call framework between Apps, letting the AI control third-party Apps that support the protocol.",
"Follow current chat (auto)","Save a Memory","Optimize Old Website Rendering",
"© 2025 - 2026 Zorv AI. All rights reserved.","Floating Voice Ball",
"If not specified, use the current / most recent session.","Reload failed","Remove","Shizuku authorized ✓",
"Soul Card Name","Open","Button","Hatching…",
"Find an input box on screen and fill in text. Locate it via hint/text/description.","Max Memory MB",
"⚠ Token expired, please tap \"Get WeChat Login QR Code\" below to scan again","💭 Thinking Process",
"License","Settings · Settings","Ask (confirm each time)",
"Enter a keyword then tap search (repository / code / Issue / user)","Import plugin from link","Key Points Summary",
"Execute commands in the self-developed sandbox terminal QuroTerm (ls/cd/cat/echo/grep/ps/top/netstat/ping/curl/wget/dns/",
"Cleared default ACI app","View/Edit Engine Script","(No web content)","Memory Usage","Content",
"Flowchart / Visualization","Send HTTP request and return response","Text Design","Source Address",
"End date (optional, empty = repeat forever)","QuroWorkspace (app sandbox)","FTP server operation failed",
"User-Agent Switch","Local Office Editor","Configured","Send install command to terminal",
"Zorv AI only launches the system dialer, does not auto-call out.","Knowledge base exported","Local Office Document",
"Remove Favorite","After closing, auto-read / chat voice button etc. still work independently per their own switches.",
"UI parse failed","Read-only SQL (SELECT/PRAGMA/WITH)",
"📐 Background AIP layout synthesis: structured layout for full long documents / PPT / reports / mind maps.",
"New Branch","Need the GenUI native interface? Have the AI open the built-in GenUI Agent with genui_agent_open.",
"Rebind","Set as Default",
"AI controls the app's built-in browser (takes over the currently displayed WebView; when the page is loaded you can directly see/operate content).",
"llama.cpp folder (select folder)","Add and Select",
"LSPosed/Xposed manager not detected (this app runs without Xposed)",
"Health data may come from multiple Apps (watch, Google Fit, this app, etc.). Grouped by DataOrigin.packageName, you can distinguish and prefer data entered by this app.",
"Bootstrap Script","Bot running in background","Find…",
"Select a soul card; the AI will communicate with you as its identity",
"Two independent controls, no mutual influence. On = 100% proactive use; Off = only when the user reminds.",
"Template (click to fill example)","Unsupported file type or file too large (>1MB)","Register and Start",
"No local model yet. After importing by any of the above methods, tap the list item to set it as the current chat model.",
"Source empty","Tap \"New\" to create your first soul card",
"File name (e.g. Main.kt / app.py / index.html)","Deploy log:",
"Execute global system-level actions: back (return), home (home), recents (recent tasks), notifications (expand notification bar), lock_screen (lock screen).",
"New Chat","Compile Project","kind only supports http / intent / broadcast",
"One-click Install Built-in Plugin","No raw output yet","Package ID",
"Speech Synthesis · Speech Recognition · Voice Settings, unified entry.","Save Only","Package name or app name",
"Upgrade","Download Instructions","⚠ Contains dependencies to resolve","No other chat yet.","Avatar",
"Edit Preset","Save and Continue Adding","Generate New Signature","Open Document",
"Voice description (e.g.: gentle girlish voice)","Open homepage in browser","Configure Visual Question",
"Get WeChat Login QR Code","Collapse Layout Preview","Local Diagnostics","Type:",
"Re-instantiate the plugin entry; changes take effect immediately",
"Validate whether a dynamic UI DSL (JSON) can be parsed correctly. Self-check before output avoids render failure.",
"Example: my DeepSeek","You","Extension Point / AI Tools / Version Info","Copy Code","Save and Preview",
"Set; a reminder notification will pop up in about 10 seconds","Uninstall failed","Fields (comma-separated)","Move to…",
"No output yet. Install/search/list command output appears here after execution (truncated to 4000 chars).",
"Document:","Freeze or unfreeze a specified app (frozen apps don't reside in memory or receive push).",
"Options are in the floating window on screen; just tap it",
"Text-to-speech config. Reading and the floating voice ball both follow this setting; the voice engine is taken over by the phone's system default TTS engine (local system) or the selected cloud provider (cloud model service).",
"This provider needs no key/params to use (e.g. Edge TTS).",
"Call CMS capability module (old interface, recommend cms_toolbox)","Log in to GitHub",
"Tasker trigger missing workflow / workflow_id / prompt","Unknown type","Share",
"Forbidden (any escalation is denied)","Please select date and time first",
"No history session yet; you can use \"Auto-create Session\"","Probing permissions…","Favorite this page",
"Please allow CapOS in the Root manager","Bio (optional)","Model Type","Java Source","About Zorv AI",
"Real-time Generation","Yansheng","Deploy to Terminal",
"Unified config for voice ball, auto-read, chat voice button and emotion / voice-role capabilities. Each switch is independent.",
"Preview Text","Export Knowledge Base (ZIP)","Add to Desktop",
"🖼️ Image Content Recognition: analyze the image file provided by the user, return a detailed description.",
"All install commands sent to terminal",
"Query CMS v2 modules and recent task execution status (deploy state / running / task terminal), let the AI confirm \"deploy/call succeeded\".",
"Paste Mermaid source to view / edit (AI can write directly to a named project with the visual tool)",
"The connection list does not auto-refresh","Folder Name","Install Sample Package",
"Control the ACI HTTP mock server (used when the real ACI API is not done yet).",
"Disable Image Loading",
"When on, local models can call tools via function calling. Off is pure chat mode, saving context window.",
"Steps in last 7 days (by source):","Repeat","Copy to…",
"(No instruction, won't inject even if enabled)","Please select authorization level:","Render to Chat",
"Cannot render GenUI content","User","Proxy Address","Checking provider health status...","Connection failed",
"Cannot auto-open the Shizuku manager; please manually open the Shizuku app and authorize this app",
"Go to Settings→Apps→Zorv AI→Notifications/Permissions to enable \"Exact Alarm\"",
"Call a capability exposed by a third-party App via ACI (Agent Capability Interface) (e.g. send message / check unread / create group / open web / run web JS / initiate HTTP request / shared workspace read-write workspace_write·workspace_read·workspace_list·workspace_delete).",
"Add Custom Tag","Update","Chat Settings","Generating","Custom UA String","Official github.com",
"Edit Provider","Allow Permanently",
"Zorv AI doesn't store email; sending is done via your chosen email app.","Device Admin Permission","Launch App",
"The data format returned by the AI is incorrect; please retry or adjust the description.",
"Evaluate Arithmetic Expression","Empty / 0 means auto. After changing, re-tap \"Load\" to take effect.",
"Background generate real files (docx/xlsx/pptx/pdf are binary, md/txt/csv/html are plain text), openable with the in-app viewer or WPS / Office.",
"Runtime permissions pop the system authorization dialog; ROOT / Shizuku / Device Admin require your active authorization in the system UI. All permission usage is recorded in the audit log.",
"Clear and Continue","Terminal · Node Runtime","Create a folder in the default workspace","Type",
"Layout failed, shown as plain text",
"Query the deployment readiness, health, version, launched shared services (NODE/PYTHON/SSH/JAVA/RUST/GO runtimes), deploy progress and logs of the \"CMS Engine (system resource package)\".",
"List currently connected external MCP servers (alias and address). View available servers with this tool before calling external tools.",
"Private Database","Say something...","AI Thinking Panel",
"Use GitHub as a search engine inside the chat: directly search GitHub's repositories / code / Issues / users.",
"No scheduled task yet","Title shown in the chat","Paste",
"Please copy the content below and send it to the developer to locate the real cause of \"settings crash / cannot chat\".",
"Export All Skills (JSON)","Terminal Environment","Failed to read file or content is empty",
"Deploy a local MCP server: submit a set of tool definitions (JSON array), the app starts an MCP endpoint locally,",
"Expand Chat",
"Models running offline on the phone must be downloaded first. All built-in are streaming transducers (encoder/decoder/joiner trio), sorted by phone adaptation; the first item is recommended. Auto-unzip and deploy after download, ready to use immediately.",
"Shizuku not running, opening and waiting for service to start…","Package Management (Linux sandbox)",
"Select preset UA or custom","✓ Login succeeded!","Memory Details","entry.sh Script",
"⚠️ No params configured, please enter config first","Project Address",
"Voice Name (free to fill)","E.g. alloy / custom gateway voice ID / or select clone voice above",
"DataOrigin grouping · this app's source is traceable","Skill Instruction (inject system prompt)",
"Ask render channel each round","Developer","👁 Eye Screenshot (page pixels)","No thinking process yet",
"☁ Cloud Port LLM","Java Project → DEX → APK",
"Multi-step workflow orchestration engine: chain registered tools into a pipeline, supports variables, loops, conditions, error handling and timeouts; use it to orchestrate other tools to fill capability gaps.",
"Compute Backend","Plugin Desktop","Send SMS","Select local document…","Control Device Volume",
"Get Current Date and Time","Terminal environment ready ✓",
"The following params only affect the local offline model, independent of cloud model settings.",
"No registered tool yet.",
"Each project uses a different package name, so installs won't conflict (over-install also needs same signature).",
"Open the web browser and navigate to the specified URL","Enable Failover",
"Local Git version control integration: run git commands on the device-storage repo inside the proot container.",
"Direct Official Gateway","Verify built-in skill signature (signature troubleshooting)",
"Already has privileged channel; can execute ADB shell directly in the terminal",
"Enter token budget (0=unlimited). Long chats auto-discard oldest rounds, always keep identity/persona/tool guidance, avoid window overflow causing lost context or broken tool calls. Xiaomi MiMo recommends 16000–32000.",
"When \"Local Model (on-device)\" is selected, this test uses the phone's offline Sherpa-NCNN recognition; other engines use native SpeechRecognizer.",
"Local Recognition","Select Question Method","ZorvAI Sandbox Terminal","Recognized text shows here",
"Terminal · Static HTTP Service","Cannot share this file (path not allowed)","Save Changes","HTML App",
"Target has a same-name file",
]

assert len(EN) == 400, (len(EN), "expected 400 entries for lines 701-1100")
out = {}
for i, t in enumerate(src[700:1100]):  # 0-based index 700..1099 → file lines 701..1100
    out[t] = EN[i]
json.dump(out, open(os.path.join(HERE, 'i18n_en_3.json'), 'w', encoding='utf-8'),
          ensure_ascii=False, indent=0)
print('wrote i18n_en_3.json with', len(out), 'entries; source slice', len(src[700:1100]))
# 校验：所有源串都在 data 里
data = json.load(open(os.path.join(HERE, 'i18n_strings.json'), encoding='utf-8'))
indata = set(e['text'] for e in data)
missing = [t for t in out if t not in indata]
print('missing from i18n_strings.json:', len(missing))
for m in missing[:10]:
    print('  ', repr(m))
