package com.ai.assistance.quro.core.novaterm.ui

import androidx.compose.ui.graphics.Color

/**
 * QuroTerm 主题系统
 * 多套赛博朋克/极客风格主题
 */
data class TerminalTheme(
    val name: String,
    val background: Color,
    val backgroundSecondary: Color,
    val foreground: Color,
    val promptColor: Color,
    val cursorColor: Color,
    val selectionColor: Color,
    val // 命令输出颜色
    outputNormal: Color,
    val outputError: Color,
    val outputSuccess: Color,
    val outputWarning: Color,
    val outputInfo: Color,
    val outputDebug: Color,
    val outputCyan: Color,
    val outputMagenta: Color,
    val outputYellow: Color,
    val outputGreen: Color,
    val outputRed: Color,
    val outputBlue: Color,
    val outputBold: Color,
    val outputDim: Color,
    // UI 元素
    val toolbarBg: Color,
    val toolbarFg: Color,
    val statusBarBg: Color,
    val statusBarFg: Color,
    val inputBg: Color,
    val inputFg: Color,
    val cardBg: Color,
    val cardBorder: Color,
    val divider: Color,
    // 特效
    val scanlineAlpha: Float,
    val glowIntensity: Float,
    val fontFamily: String = "monospace"
)

object Themes {
    val Matrix = TerminalTheme(
        name = "Matrix",
        background = Color(0xFF0A0A0A),
        backgroundSecondary = Color(0xFF121212),
        foreground = Color(0xFF00FF41),
        promptColor = Color(0xFF00FF41),
        cursorColor = Color(0xFF00FF41),
        selectionColor = Color(0xFF1A3A1A),
        outputNormal = Color(0xFF00FF41),
        outputError = Color(0xFFFF0040),
        outputSuccess = Color(0xFF00FF80),
        outputWarning = Color(0xFFFFAA00),
        outputInfo = Color(0xFF00AAFF),
        outputDebug = Color(0xFF666666),
        outputCyan = Color(0xFF00FFFF),
        outputMagenta = Color(0xFFFF00FF),
        outputYellow = Color(0xFFFFFF00),
        outputGreen = Color(0xFF00FF41),
        outputRed = Color(0xFFFF0040),
        outputBlue = Color(0xFF0080FF),
        outputBold = Color(0xFFAAFFAA),
        outputDim = Color(0xFF005015),
        toolbarBg = Color(0xFF0D200D),
        toolbarFg = Color(0xFF00FF41),
        statusBarBg = Color(0xFF0D200D),
        statusBarFg = Color(0xFF008020),
        inputBg = Color(0xFF050505),
        inputFg = Color(0xFF00FF41),
        cardBg = Color(0xFF0D150D),
        cardBorder = Color(0xFF1A3A1A),
        divider = Color(0xFF1A3A1A),
        scanlineAlpha = 0.03f,
        glowIntensity = 0.8f
    )

    val Cyberpunk = TerminalTheme(
        name = "Cyberpunk",
        background = Color(0xFF0D0221),
        backgroundSecondary = Color(0xFF150D2E),
        foreground = Color(0xFFF8F8FF),
        promptColor = Color(0xFFFF006E),
        cursorColor = Color(0xFF00F5FF),
        selectionColor = Color(0xFF3A0A6E),
        outputNormal = Color(0xFFE0E0FF),
        outputError = Color(0xFFFF006E),
        outputSuccess = Color(0xFF00F5FF),
        outputWarning = Color(0xFFFFBE0B),
        outputInfo = Color(0xFF8338EC),
        outputDebug = Color(0xFF6C757D),
        outputCyan = Color(0xFF00F5FF),
        outputMagenta = Color(0xFFFF006E),
        outputYellow = Color(0xFFFFBE0B),
        outputGreen = Color(0xFF00FF88),
        outputRed = Color(0xFFFF006E),
        outputBlue = Color(0xFF3A86FF),
        outputBold = Color(0xFFFFFFFF),
        outputDim = Color(0xFF6C6C8A),
        toolbarBg = Color(0xFF1A0A3E),
        toolbarFg = Color(0xFF00F5FF),
        statusBarBg = Color(0xFF1A0A3E),
        statusBarFg = Color(0xFFFF006E),
        inputBg = Color(0xFF0A0115),
        inputFg = Color(0xFFF8F8FF),
        cardBg = Color(0xFF150D2E),
        cardBorder = Color(0xFF3A0A6E),
        divider = Color(0xFF3A0A6E),
        scanlineAlpha = 0.04f,
        glowIntensity = 1.0f
    )

    val Dracula = TerminalTheme(
        name = "Dracula",
        background = Color(0xFF282A36),
        backgroundSecondary = Color(0xFF1E1F29),
        foreground = Color(0xFFF8F8F2),
        promptColor = Color(0xFF50FA7B),
        cursorColor = Color(0xFFF8F8F2),
        selectionColor = Color(0xFF44475A),
        outputNormal = Color(0xFFF8F8F2),
        outputError = Color(0xFFFF5555),
        outputSuccess = Color(0xFF50FA7B),
        outputWarning = Color(0xFFFFB86C),
        outputInfo = Color(0xFF8BE9FD),
        outputDebug = Color(0xFF6272A4),
        outputCyan = Color(0xFF8BE9FD),
        outputMagenta = Color(0xFFF5A623),  // 修正为更亮的橙色
        outputYellow = Color(0xFFFFB86C),
        outputGreen = Color(0xFF50FA7B),
        outputRed = Color(0xFFFF5555),
        outputBlue = Color(0xFFBD93F9),
        outputBold = Color(0xFFFFFFFF),
        outputDim = Color(0xFF6272A4),
        toolbarBg = Color(0xFF1E1F29),
        toolbarFg = Color(0xFF50FA7B),
        statusBarBg = Color(0xFF1E1F29),
        statusBarFg = Color(0xFF6272A4),
        inputBg = Color(0xFF21222C),
        inputFg = Color(0xFFF8F8F2),
        cardBg = Color(0xFF21222C),
        cardBorder = Color(0xFF44475A),
        divider = Color(0xFF44475A),
        scanlineAlpha = 0.0f,
        glowIntensity = 0.3f
    )

    val Nord = TerminalTheme(
        name = "Nord",
        background = Color(0xFF2E3440),
        backgroundSecondary = Color(0xFF242933),
        foreground = Color(0xFFD8DEE9),
        promptColor = Color(0xFF88C0D0),
        cursorColor = Color(0xFFD8DEE9),
        selectionColor = Color(0xFF434C5E),
        outputNormal = Color(0xFFD8DEE9),
        outputError = Color(0xFFBF616A),
        outputSuccess = Color(0xFFA3BE8C),
        outputWarning = Color(0xFFEBCB8B),
        outputInfo = Color(0xFF88C0D0),
        outputDebug = Color(0xFF4C566A),
        outputCyan = Color(0xFF8FBCBB),
        outputMagenta = Color(0xFFB48EAD),
        outputYellow = Color(0xFFEBCB8B),
        outputGreen = Color(0xFFA3BE8C),
        outputRed = Color(0xFFBF616A),
        outputBlue = Color(0xFF81A1C1),
        outputBold = Color(0xFFECEFF4),
        outputDim = Color(0xFF4C566A),
        toolbarBg = Color(0xFF242933),
        toolbarFg = Color(0xFF88C0D0),
        statusBarBg = Color(0xFF242933),
        statusBarFg = Color(0xFF4C566A),
        inputBg = Color(0xFF3B4252),
        inputFg = Color(0xFFD8DEE9),
        cardBg = Color(0xFF3B4252),
        cardBorder = Color(0xFF434C5E),
        divider = Color(0xFF434C5E),
        scanlineAlpha = 0.0f,
        glowIntensity = 0.2f
    )

    val Solarized = TerminalTheme(
        name = "Solarized",
        background = Color(0xFF002B36),
        backgroundSecondary = Color(0xFF073642),
        foreground = Color(0xFF839496),
        promptColor = Color(0xFFB58900),
        cursorColor = Color(0xFF93A1A1),
        selectionColor = Color(0xFF073642),
        outputNormal = Color(0xFF839496),
        outputError = Color(0xFFDC322F),
        outputSuccess = Color(0xFF859900),
        outputWarning = Color(0xFFCB4B16),
        outputInfo = Color(0xFF268BD2),
        outputDebug = Color(0xFF586E75),
        outputCyan = Color(0xFF2AA198),
        outputMagenta = Color(0xFFD33682),
        outputYellow = Color(0xFFB58900),
        outputGreen = Color(0xFF859900),
        outputRed = Color(0xFFDC322F),
        outputBlue = Color(0xFF268BD2),
        outputBold = Color(0xFFFDF6E3),
        outputDim = Color(0xFF586E75),
        toolbarBg = Color(0xFF073642),
        toolbarFg = Color(0xFFB58900),
        statusBarBg = Color(0xFF073642),
        statusBarFg = Color(0xFF586E75),
        inputBg = Color(0xFF001B24),
        inputFg = Color(0xFF839496),
        cardBg = Color(0xFF073642),
        cardBorder = Color(0xFF0A4656),
        divider = Color(0xFF0A4656),
        scanlineAlpha = 0.0f,
        glowIntensity = 0.3f
    )

    val allThemes = listOf(Matrix, Cyberpunk, Dracula, Nord, Solarized)

    fun getByName(name: String): TerminalTheme =
        allThemes.firstOrNull { it.name.equals(name, ignoreCase = true) } ?: Matrix
}
