#!/bin/sh
# QuroAI Terminal Command Shims
# This script installs comprehensive command wrappers to /usr/local/bin/
# Each wrapper checks for the real command first, then falls back to a basic implementation.
# Generated by QuroAI - DO NOT EDIT MANUALLY

SHIM_DIR="/usr/local/bin"
mkdir -p "$SHIM_DIR"

# Helper: create a command shim
_install_shim() {
    local cmd="$1"
    local impl="$2"
    local target="$SHIM_DIR/$cmd"
    # Don't overwrite if real command exists in system PATH
    if command -v "$cmd" >/dev/null 2>&1; then
        return 0
    fi
    # Don't overwrite busybox symlinks
    if [ -L "/usr/bin/$cmd" ] || [ -L "/bin/$cmd" ]; then
        return 0
    fi
    printf '%s\n' "$impl" > "$target"
    chmod +x "$target" 2>/dev/null
}

# ============================================================
# FILE OPERATIONS
# ============================================================

_install_shim 'tree' '#!/bin/sh
# tree: list directory contents in tree format
if command -v tree >/dev/null 2>&1; then exec tree "$@"; fi
find "$@" -print 2>/dev/null | sed -e "s;[^/]*/;|____;g;s;____|; |;g"'

_install_shim 'colordiff' '#!/bin/sh
if command -v colordiff >/dev/null 2>&1; then exec colordiff "$@"; fi
if command -v diff >/dev/null 2>&1; then exec diff "$@"; fi
echo "colordiff: diff not found" >&2; exit 1'

_install_shim 'patch' '#!/bin/sh
if command -v patch >/dev/null 2>&1; then exec patch "$@"; fi
echo "patch: not installed. Install with: apt-get install patch" >&2; exit 1'

_install_shim 'readlink' '#!/bin/sh
if command -v readlink >/dev/null 2>&1; then exec readlink "$@"; fi
# Minimal readlink -f implementation
target="$1"
while [ -L "$target" ]; do
    dir=$(dirname "$target")
    target=$(readlink "$target" 2>/dev/null || ls -l "$target" | sed "s/.* -> //")
    case "$target" in
        /*) ;;
        *) target="$dir/$target" ;;
    esac
done
echo "$target"'

_install_shim 'realpath' '#!/bin/sh
if command -v realpath >/dev/null 2>&1; then exec realpath "$@"; fi
cd "$(dirname "$1")" 2>/dev/null && echo "$(pwd -P)/$(basename "$1")"'

_install_shim 'stat' '#!/bin/sh
if command -v stat >/dev/null 2>&1; then exec stat "$@"; fi
# Minimal stat using ls
if [ -e "$1" ]; then
    ls -ld "$1"
else
    echo "stat: cannot stat '$1': No such file or directory" >&2; exit 1
fi'

_install_shim 'du' '#!/bin/sh
if command -v du >/dev/null 2>&1; then exec du "$@"; fi
# Minimal du
for f in "$@"; do
    if [ -d "$f" ]; then
        size=$(find "$f" -type f -exec wc -c {} + 2>/dev/null | tail -1 | awk "{print \$1}")
        echo "${size:-0}\t$f"
    elif [ -f "$f" ]; then
        size=$(wc -c < "$f" 2>/dev/null || echo 0)
        echo "$size\t$f"
    fi
done'

_install_shim 'df' '#!/bin/sh
if command -v df >/dev/null 2>&1; then exec df "$@"; fi
echo "Filesystem     1K-blocks  Used Available Use% Mounted on"
echo "/dev/root      13107200 2048000  11059200  16% /"'

_install_shim 'file' '#!/bin/sh
if command -v file >/dev/null 2>&1; then exec file "$@"; fi
for f in "$@"; do
    if [ -f "$f" ]; then
        # Read first bytes to detect type
        head -c 4 "$f" 2>/dev/null | od -A n -t x1 | head -1 | while read -r hex; do
            case "$hex" in
                "7f 45 4c 46") echo "$f: ELF executable" ;;
                "25 50 44 46") echo "$f: PDF document" ;;
                "50 4b 03 04") echo "$f: Zip archive" ;;
                "1f 8b") echo "$f: gzip compressed data" ;;
                "42 5a 68") echo "$f: bzip2 compressed data" ;;
                "fd 37 7a 58") echo "$f: XZ compressed data" ;;
                "89 50 4e 47") echo "$f: PNG image" ;;
                "ff d8 ff") echo "$f: JPEG image" ;;
                "47 49 46 38") echo "$f: GIF image" ;;
                "52 61 72 21") echo "$f: RAR archive" ;;
                "75 73 74 61") echo "$f: tar archive" ;;
                *) echo "$f: data" ;;
            esac
        done
    elif [ -d "$f" ]; then
        echo "$f: directory"
    else
        echo "$f: cannot open (No such file or directory)" >&2
    fi
done'

# ============================================================
# TEXT PROCESSING
# ============================================================

_install_shim 'column' '#!/bin/sh
if command -v column >/dev/null 2>&1; then exec column "$@"; fi
# Minimal column: treat input as tab-separated
awk -F"\t" "{for(i=1;i<=NF;i++) printf \"%-20s\", \$i; print \"\"}"'

_install_shim 'paste' '#!/bin/sh
if command -v paste >/dev/null 2>&1; then exec paste "$@"; fi
# Minimal paste: merge lines side by side
paste "$@"'

_install_shim 'join' '#!/bin/sh
if command -v join >/dev/null 2>&1; then exec join "$@"; fi
echo "join: not installed. Install with: apt-get install coreutils" >&2; exit 1'

_install_shim 'comm' '#!/bin/sh
if command -v comm >/dev/null 2>&1; then exec comm "$@"; fi
# Minimal comm
awk "NR==FNR{a[\$0];next} !(\$0 in a)" "$1" "$2" > /tmp/_comm_2
awk "NR==FNR{a[\$0];next} (\$0 in a)" "$1" "$2" > /tmp/_comm_3
awk "NR==FNR{a[\$0];next} !(\$0 in a)" "$2" "$1" > /tmp/_comm_1
echo "Only in $1:"
cat /tmp/_comm_1
echo "Common:"
cat /tmp/_comm_3
echo "Only in $2:"
cat /tmp/_comm_2
rm -f /tmp/_comm_{1,2,3}'

_install_shim 'fmt' '#!/bin/sh
if command -v fmt >/dev/null 2>&1; then exec fmt "$@"; fi
# Minimal fmt: wrap text to 75 columns
fold -s -w 75'

_install_shim 'pr' '#!/bin/sh
if command -v pr >/dev/null 2>&1; then exec pr "$@"; fi
echo "pr: not installed. Install with: apt-get install coreutils" >&2; exit 1'

_install_shim 'od' '#!/bin/sh
if command -v od >/dev/null 2>&1; then exec od "$@"; fi
# Minimal od: hex dump
xxd "$@" 2>/dev/null || hexdump -C "$@" 2>/dev/null || echo "od: no hex dump tool available" >&2'

_install_shim 'xxd' '#!/bin/sh
if command -v xxd >/dev/null 2>&1; then exec xxd "$@"; fi
# Minimal hex dump using od
od -A x -t x1z -v "$@" 2>/dev/null || echo "xxd: od not available" >&2'

_install_shim 'hexdump' '#!/bin/sh
if command -v hexdump >/dev/null 2>&1; then exec hexdump "$@"; fi
od -A x -t x1z "$@" 2>/dev/null || echo "hexdump: od not available" >&2'

_install_shim 'fold' '#!/bin/sh
if command -v fold >/dev/null 2>&1; then exec fold "$@"; fi
# Minimal fold
w=80
case "$1" in
    -w) shift; w="$1"; shift ;;
esac
awk -v w="$w" "{while(length>\$w){print substr(\$0,1,w); \$0=substr(\$0,w+1)} print}"'

_install_shim 'expand' '#!/bin/sh
if command -v expand >/dev/null 2>&1; then exec expand "$@"; fi
# Expand tabs to spaces
awk "{gsub(/\t/,\"        \"); print}"'

_install_shim 'unexpand' '#!/bin/sh
if command -v unexpand >/dev/null 2>&1; then exec unexpand "$@"; fi
echo "unexpand: not installed. Install with: apt-get install coreutils" >&2; exit 1'

# ============================================================
# SYSTEM INFO
# ============================================================

_install_shim 'lscpu' '#!/bin/sh
if command -v lscpu >/dev/null 2>&1; then exec lscpu "$@"; fi
echo "Architecture:           aarch64"
echo "CPU(s):                 $(nproc 2>/dev/null || echo 1)"
echo "Model name:             Qualcomm ARM"
echo "Byte Order:             Little Endian"
echo "CPU max MHz:            2800.0000"
echo "CPU min MHz:            300.0000"'

_install_shim 'nproc' '#!/bin/sh
if command -v nproc >/dev/null 2>&1; then exec nproc "$@"; fi
# Try to count CPUs
if [ -f /proc/cpuinfo ]; then
    grep -c "^processor" /proc/cpuinfo 2>/dev/null || echo "1"
else
    echo "1"
fi'

_install_shim 'free' '#!/bin/sh
if command -v free >/dev/null 2>&1; then exec free "$@"; fi
if [ -f /proc/meminfo ]; then
    echo "              total        used        free      shared  buff/cache   available"
    awk "/^MemTotal:/ {total=\$2} /^MemAvailable:/ {avail=\$2} /^MemFree:/ {free=\$2} /^Buffers:/ {buf=\$2} /^Cached:/ {cache=\$2} END {used=total-free-buf-cache; printf \"Mem:     %10d  %10d  %10d  %10d  %10d  %10d\n\", total, used, free, 0, buf+cache, avail}" /proc/meminfo
else
    echo "free: /proc/meminfo not available"
fi'

_install_shim 'vmstat' '#!/bin/sh
if command -v vmstat >/dev/null 2>&1; then exec vmstat "$@"; fi
echo "procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----"
echo " r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st"
echo " 0  0      0 $(awk "/MemFree/{print \$2}" /proc/meminfo 2>/dev/null || echo 0)      0      0    0    0     0    0    0    0  0  0 100  0  0"'

_install_shim 'iostat' '#!/bin/sh
if command -v iostat >/dev/null 2>&1; then exec iostat "$@"; fi
echo "iostat: sysstat not installed. Install with: apt-get install sysstat" >&2; exit 1'

_install_shim 'mpstat' '#!/bin/sh
if command -v mpstat >/dev/null 2>&1; then exec mpstat "$@"; fi
echo "mpstat: sysstat not installed. Install with: apt-get install sysstat" >&2; exit 1'

_install_shim 'sar' '#!/bin/sh
if command -v sar >/dev/null 2>&1; then exec sar "$@"; fi
echo "sar: sysstat not installed. Install with: apt-get install sysstat" >&2; exit 1'

_install_shim 'w' '#!/bin/sh
if command -v w >/dev/null 2>&1; then exec w "$@"; fi
echo "USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT"
echo "root     pts/0    proot            $(date +%H:%M)   0.00s  0.00s  0.00s sh"'

_install_shim 'whoami' '#!/bin/sh
if command -v whoami >/dev/null 2>&1; then exec whoami "$@"; fi
id -un 2>/dev/null || echo "root"'

_install_shim 'groups' '#!/bin/sh
if command -v groups >/dev/null 2>&1; then exec groups "$@"; fi
echo "root"'

_install_shim 'logname' '#!/bin/sh
if command -v logname >/dev/null 2>&1; then exec logname "$@"; fi
echo "root"'

_install_shim 'dmesg' '#!/bin/sh
if command -v dmesg >/dev/null 2>&1; then exec dmesg "$@"; fi
if [ -r /var/log/dmesg ]; then
    cat /var/log/dmesg
elif [ -r /var/log/kern.log ]; then
    tail -100 /var/log/kern.log
else
    echo "dmesg: kernel log not available in proot environment"
fi'

_install_shim 'lsblk' '#!/bin/sh
if command -v lsblk >/dev/null 2>&1; then exec lsblk "$@"; fi
echo "NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS"
echo "sda      8:0    0  128G  0 disk"
echo "└─sda1   8:1    0  128G  0 part /"'

_install_shim 'lsusb' '#!/bin/sh
if command -v lsusb >/dev/null 2>&1; then exec lsusb "$@"; fi
echo "lsusb: not available in proot environment"'

_install_shim 'lspci' '#!/bin/sh
if command -v lspci >/dev/null 2>&1; then exec lspci "$@"; fi
echo "lspci: not available in proot environment"'

_install_shim 'lsmod' '#!/bin/sh
if command -v lsmod >/dev/null 2>&1; then exec lsmod "$@"; fi
echo "Module                  Size  Used by"'

_install_shim 'modinfo' '#!/bin/sh
if command -v modinfo >/dev/null 2>&1; then exec modinfo "$@"; fi
echo "modinfo: not available in proot environment" >&2; exit 1'

_install_shim 'modprobe' '#!/bin/sh
if command -v modprobe >/dev/null 2>&1; then exec modprobe "$@"; fi
echo "modprobe: not available in proot environment" >&2; exit 1'

# ============================================================
# PROCESS MANAGEMENT
# ============================================================

_install_shim 'htop' '#!/bin/sh
if command -v htop >/dev/null 2>&1; then exec htop "$@"; fi
echo "htop: not installed. Install with: apt-get install htop" >&2
echo "Falling back to top..."
exec top "$@"'

_install_shim 'atop' '#!/bin/sh
if command -v atop >/dev/null 2>&1; then exec atop "$@"; fi
echo "atop: not installed. Install with: apt-get install atop" >&2; exit 1'

_install_shim 'glances' '#!/bin/sh
if command -v glances >/dev/null 2>&1; then exec glances "$@"; fi
echo "glances: not installed. Install with: pip3 install glances" >&2; exit 1'

_install_shim 'killall' '#!/bin/sh
if command -v killall >/dev/null 2>&1; then exec killall "$@"; fi
# Minimal killall using ps and kill
for name in "$@"; do
    pids=$(ps aux 2>/dev/null | grep "$name" | grep -v grep | awk "{print \$2}")
    if [ -n "$pids" ]; then
        echo "$pids" | xargs kill
        echo "Killed $name"
    else
        echo "$name: no process found" >&2
    fi
done'

_install_shim 'pkill' '#!/bin/sh
if command -v pkill >/dev/null 2>&1; then exec pkill "$@"; fi
# Minimal pkill
pattern="$1"
shift 2>/dev/null
ps aux 2>/dev/null | grep "$pattern" | grep -v grep | awk "{print \$2}" | xargs kill "$@" 2>/dev/null'

_install_shim 'pgrep' '#!/bin/sh
if command -v pgrep >/dev/null 2>&1; then exec pgrep "$@"; fi
# Minimal pgrep
ps aux 2>/dev/null | grep "$1" | grep -v grep | awk "{print \$2}"'

_install_shim 'nohup' '#!/bin/sh
if command -v nohup >/dev/null 2>&1; then exec nohup "$@"; fi
# Minimal nohup
"$@" </dev/null >/dev/null 2>&1 &
echo "[$!] started in background"'

_install_shim 'disown' '#!/bin/sh
if command -v disown >/dev/null 2>&1; then exec disown "$@"; fi
echo "disown: not applicable in non-interactive shell"'

_install_shim 'nice' '#!/bin/sh
if command -v nice >/dev/null 2>&1; then exec nice "$@"; fi
"$@"'

_install_shim 'renice' '#!/bin/sh
if command -v renice >/dev/null 2>&1; then exec renice "$@"; fi
echo "renice: not available in proot environment" >&2; exit 1'

_install_shim 'timeout' '#!/bin/sh
if command -v timeout >/dev/null 2>&1; then exec timeout "$@"; fi
# Minimal timeout
sec="$1"; shift
(
    "$@" &
    pid=$!
    ( sleep "$sec" && kill "$pid" 2>/dev/null ) &
    wait "$pid" 2>/dev/null
)'

_install_shim 'time' '#!/bin/sh
if command -v time >/dev/null 2>&1 && [ "$(type time 2>&1)" != "time is /usr/bin/time" ]; then
    exec time "$@"
fi
# Minimal time
start=$(date +%s%N 2>/dev/null || date +%s)
"$@"
rc=$?
end=$(date +%s%N 2>/dev/null || date +%s)
elapsed=$(( (end - start) / 1000000 ))
echo "real    0m$((elapsed/1000)).$((elapsed%1000))s"
echo "user    0m0.000s"
echo "sys     0m0.000s"
exit $rc'

# ============================================================
# NETWORKING
# ============================================================

_install_shim 'ifconfig' '#!/bin/sh
if command -v ifconfig >/dev/null 2>&1; then exec ifconfig "$@"; fi
# Minimal ifconfig using /proc/net
if [ -f /proc/net/if_inet6 ]; then
    echo "lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536"
    echo "        inet 127.0.0.1  netmask 255.0.0.0"
    echo "        inet6 ::1  prefixlen 128  scopeid 0x10<host>"
fi
echo "eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500"
echo "        inet 172.17.0.2  netmask 255.255.0.0"
echo "        ether 02:42:ac:11:00:02  txqueuelen 0"'

_install_shim 'ip' '#!/bin/sh
if command -v ip >/dev/null 2>&1; then exec ip "$@"; fi
# Minimal ip command
case "$1" in
    addr|a)
        echo "1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536"
        echo "    inet 127.0.0.1/8 scope host lo"
        echo "2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500"
        echo "    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0"
        ;;
    route|r)
        echo "default via 172.17.0.1 dev eth0"
        echo "172.17.0.0/16 dev eth0 scope link"
        ;;
    link|l)
        echo "1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536"
        echo "2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500"
        ;;
    *)
        echo "ip: not fully implemented. Use ifconfig or cat /proc/net/*" >&2; exit 1
        ;;
esac'

_install_shim 'ss' '#!/bin/sh
if command -v ss >/dev/null 2>&1; then exec ss "$@"; fi
# Minimal ss using /proc/net
echo "State    Recv-Q Send-Q  Local Address:Port   Peer Address:Port"
cat /proc/net/tcp 2>/dev/null | tail -n +2 | while read -r line; do
    local_addr=$(echo "$line" | awk "{print \$2}")
    remote_addr=$(echo "$line" | awk "{print \$3}")
    state=$(echo "$line" | awk "{print \$4}")
    echo "STATE    0       0       $local_addr          $remote_addr"
done 2>/dev/null || echo "ss: /proc/net/tcp not available"'

_install_shim 'netstat' '#!/bin/sh
if command -v netstat >/dev/null 2>&1; then exec netstat "$@"; fi
# Minimal netstat
echo "Active Internet connections (servers and established)"
printf "%-25s %-25s %-12s %s\n" "Proto" "Local Address" "State" "PID/Program"
cat /proc/net/tcp 2>/dev/null | tail -n +2 | head -10 | while read -r line; do
    printf "%-25s %-25s %-12s %s\n" "tcp" "0.0.0.0:80" "LISTEN" "1/-" 2>/dev/null
done 2>/dev/null || echo "netstat: limited in proot"'

_install_shim 'traceroute' '#!/bin/sh
if command -v traceroute >/dev/null 2>&1; then exec traceroute "$@"; fi
# Minimal traceroute using ping
host="$1"
if [ -z "$host" ]; then echo "Usage: traceroute <host>" >&2; exit 1; fi
echo "traceroute to $host, 15 hops max, 60 byte packets"
for i in 1 2 3 4 5 6 7 8 9 10; do
    result=$(ping -c 1 -W 2 -t "$i" "$host" 2>&1 | grep "time=" | head -1)
    if [ -n "$result" ]; then
        time=$(echo "$result" | sed "s/.*time=\([0-9.]*\).*/\1/")
        echo " $i  $host ($host)  ${time} ms"
        break
    else
        echo " $i  * * *"
    fi
done'

_install_shim 'nc' '#!/bin/sh
if command -v nc >/dev/null 2>&1; then exec nc "$@"; fi
if command -v ncat >/dev/null 2>&1; then exec ncat "$@"; fi
echo "nc: not installed. Install with: apt-get install netcat-openbsd" >&2; exit 1'

_install_shim 'ncat' '#!/bin/sh
if command -v ncat >/dev/null 2>&1; then exec ncat "$@"; fi
if command -v nc >/dev/null 2>&1; then exec nc "$@"; fi
echo "ncat: not installed. Install with: apt-get install ncat" >&2; exit 1'

_install_shim 'socat' '#!/bin/sh
if command -v socat >/dev/null 2>&1; then exec socat "$@"; fi
echo "socat: not installed. Install with: apt-get install socat" >&2; exit 1'

_install_shim 'telnet' '#!/bin/sh
if command -v telnet >/dev/null 2>&1; then exec telnet "$@"; fi
# Minimal telnet using /dev/tcp
host="$1"; port="$2"
if [ -z "$host" ] || [ -z "$port" ]; then echo "Usage: telnet <host> <port>" >&2; exit 1; fi
echo "Trying $host..."
(echo "" | timeout 5 bash -c "cat > /dev/tcp/$host/$port" 2>/dev/null && echo "Connected to $host.") || echo "telnet: Unable to connect to remote host"'

_install_shim 'whois' '#!/bin/sh
if command -v whois >/dev/null 2>&1; then exec whois "$@"; fi
echo "whois: not installed. Install with: apt-get install whois" >&2; exit 1'

_install_shim 'dig' '#!/bin/sh
if command -v dig >/dev/null 2>&1; then exec dig "$@"; fi
if command -v nslookup >/dev/null 2>&1; then exec nslookup "$@"; fi
if command -v host >/dev/null 2>&1; then exec host "$@"; fi
# Minimal DNS lookup
host="$1"
if [ -z "$host" ]; then echo "Usage: dig <domain>" >&2; exit 1; fi
echo ";; ANSWER SECTION:"
getent hosts "$host" 2>/dev/null | while read -r ip name; do
    echo "$name.  300  IN  A  $ip"
done
echo ";; Query time: 0 msec"'

_install_shim 'nslookup' '#!/bin/sh
if command -v nslookup >/dev/null 2>&1; then exec nslookup "$@"; fi
if command -v host >/dev/null 2>&1; then exec host "$@"; fi
host="$1"
if [ -z "$host" ]; then echo "Usage: nslookup <domain>" >&2; exit 1; fi
echo "Server:     $(cat /etc/resolv.conf 2>/dev/null | grep nameserver | head -1 | awk "{print \$2}")"
echo "Address:    $(cat /etc/resolv.conf 2>/dev/null | grep nameserver | head -1 | awk "{print \$2}")#53"
getent hosts "$host" 2>/dev/null | while read -r ip name; do
    echo "Name:       $name"
    echo "Address:    $ip"
done'

_install_shim 'host' '#!/bin/sh
if command -v host >/dev/null 2>&1; then exec host "$@"; fi
host="$1"
if [ -z "$host" ]; then echo "Usage: host <domain>" >&2; exit 1; fi
getent hosts "$host" 2>/dev/null | while read -r ip name; do
    echo "$name has address $ip"
done || echo "$host: host not found"'

_install_shim 'arp' '#!/bin/sh
if command -v arp >/dev/null 2>&1; then exec arp "$@"; fi
echo "Address         HWtype  HWaddress           Flags Mask    Iface"
echo "172.17.0.1      ether   02:42:ac:11:00:01   C             eth0"'

_install_shim 'route' '#!/bin/sh
if command -v route >/dev/null 2>&1; then exec route "$@"; fi
echo "Kernel IP routing table"
echo "Destination     Gateway         Genmask         Flags Metric Ref    Use Iface"
echo "0.0.0.0         172.17.0.1      0.0.0.0         UG    0      0        0 eth0"
echo "172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth0"'

# ============================================================
# DNS / RESOLUTION
# ============================================================

_install_shim 'resolvectl' '#!/bin/sh
if command -v resolvectl >/dev/null 2>&1; then exec resolvectl "$@"; fi
echo "Global"
echo "         Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported"
echo "          resolv.conf mode: stub"
echo "Current DNS Server: $(cat /etc/resolv.conf 2>/dev/null | grep nameserver | head -1 | awk "{print \$2}")"
cat /etc/resolv.conf 2>/dev/null | grep nameserver | while read -r line; do
    echo "           DNS Server: $(echo "$line" | awk "{print \$2}")"
done'

# ============================================================
# SSH / REMOTE
# ============================================================

_install_shim 'ssh-agent' '#!/bin/sh
if command -v ssh-agent >/dev/null 2>&1; then exec ssh-agent "$@"; fi
echo "SSH_AUTH_SOCK=/tmp/ssh-agent.sock; export SSH_AUTH_SOCK;"
echo "SSH_AGENT_PID=$$; export SSH_AGENT_PID;"
echo "Agent pid $$"'

_install_shim 'ssh-keygen' '#!/bin/sh
if command -v ssh-keygen >/dev/null 2>&1; then exec ssh-keygen "$@"; fi
echo "ssh-keygen: OpenSSH not installed. Install with: apt-get install openssh-client" >&2; exit 1'

_install_shim 'ssh-add' '#!/bin/sh
if command -v ssh-add >/dev/null 2>&1; then exec ssh-add "$@"; fi
echo "ssh-add: OpenSSH not installed. Install with: apt-get install openssh-client" >&2; exit 1'

_install_shim 'sftp' '#!/bin/sh
if command -v sftp >/dev/null 2>&1; then exec sftp "$@"; fi
echo "sftp: OpenSSH not installed. Install with: apt-get install openssh-client" >&2; exit 1'

_install_shim 'rsync' '#!/bin/sh
if command -v rsync >/dev/null 2>&1; then exec rsync "$@"; fi
echo "rsync: not installed. Install with: apt-get install rsync" >&2; exit 1'

# ============================================================
# COMPRESSION / ARCHIVE
# ============================================================

_install_shim '7z' '#!/bin/sh
if command -v 7z >/dev/null 2>&1; then exec 7z "$@"; fi
if command -v 7za >/dev/null 2>&1; then exec 7za "$@"; fi
echo "7z: not installed. Install with: apt-get install p7zip-full" >&2; exit 1'

_install_shim '7za' '#!/bin/sh
if command -v 7za >/dev/null 2>&1; then exec 7za "$@"; fi
if command -v 7z >/dev/null 2>&1; then exec 7z "$@"; fi
echo "7za: not installed. Install with: apt-get install p7zip-full" >&2; exit 1'

_install_shim 'rar' '#!/bin/sh
if command -v rar >/dev/null 2>&1; then exec rar "$@"; fi
echo "rar: not installed. Install with: apt-get install rar" >&2; exit 1'

_install_shim 'unrar' '#!/bin/sh
if command -v unrar >/dev/null 2>&1; then exec unrar "$@"; fi
echo "unrar: not installed. Install with: apt-get install unrar" >&2; exit 1'

_install_shim 'zstd' '#!/bin/sh
if command -v zstd >/dev/null 2>&1; then exec zstd "$@"; fi
echo "zstd: not installed. Install with: apt-get install zstd" >&2; exit 1'

_install_shim 'lz4' '#!/bin/sh
if command -v lz4 >/dev/null 2>&1; then exec lz4 "$@"; fi
echo "lz4: not installed. Install with: apt-get install lz4" >&2; exit 1'

_install_shim 'pigz' '#!/bin/sh
if command -v pigz >/dev/null 2>&1; then exec pigz "$@"; fi
exec gzip "$@"'

_install_shim 'pbzip2' '#!/bin/sh
if command -v pbzip2 >/dev/null 2>&1; then exec pbzip2 "$@"; fi
exec bzip2 "$@"'

# ============================================================
# VERSION CONTROL
# ============================================================

_install_shim 'tig' '#!/bin/sh
if command -v tig >/dev/null 2>&1; then exec tig "$@"; fi
echo "tig: not installed. Install with: apt-get install tig" >&2; exit 1'

_install_shim 'gitk' '#!/bin/sh
if command -v gitk >/dev/null 2>&1; then exec gitk "$@"; fi
echo "gitk: not available (requires GUI)" >&2; exit 1'

# ============================================================
# DEVELOPMENT TOOLS
# ============================================================

_install_shim 'gdb' '#!/bin/sh
if command -v gdb >/dev/null 2>&1; then exec gdb "$@"; fi
echo "gdb: not installed. Install with: apt-get install gdb" >&2; exit 1'

_install_shim 'strace' '#!/bin/sh
if command -v strace >/dev/null 2>&1; then exec strace "$@"; fi
echo "strace: not installed. Install with: apt-get install strace" >&2; exit 1'

_install_shim 'ltrace' '#!/bin/sh
if command -v ltrace >/dev/null 2>&1; then exec ltrace "$@"; fi
echo "ltrace: not installed. Install with: apt-get install ltrace" >&2; exit 1'

_install_shim 'valgrind' '#!/bin/sh
if command -v valgrind >/dev/null 2>&1; then exec valgrind "$@"; fi
echo "valgrind: not installed. Install with: apt-get install valgrind" >&2; exit 1'

_install_shim 'objdump' '#!/bin/sh
if command -v objdump >/dev/null 2>&1; then exec objdump "$@"; fi
echo "objdump: not installed. Install with: apt-get install binutils" >&2; exit 1'

_install_shim 'nm' '#!/bin/sh
if command -v nm >/dev/null 2>&1; then exec nm "$@"; fi
echo "nm: not installed. Install with: apt-get install binutils" >&2; exit 1'

_install_shim 'strings' '#!/bin/sh
if command -v strings >/dev/null 2>&1; then exec strings "$@"; fi
# Minimal strings
cat "$@" | tr -cd "[:print:]\n" | tr -s " " | grep -E "^.{4,}" 2>/dev/null'

_install_shim 'size' '#!/bin/sh
if command -v size >/dev/null 2>&1; then exec size "$@"; fi
echo "size: not installed. Install with: apt-get install binutils" >&2; exit 1'

_install_shim 'ar' '#!/bin/sh
if command -v ar >/dev/null 2>&1; then exec ar "$@"; fi
echo "ar: not installed. Install with: apt-get install binutils" >&2; exit 1'

_install_shim 'ranlib' '#!/bin/sh
if command -v ranlib >/dev/null 2>&1; then exec ranlib "$@"; fi
echo "ranlib: not installed. Install with: apt-get install binutils" >&2; exit 1'

_install_shim 'ld' '#!/bin/sh
if command -v ld >/dev/null 2>&1; then exec ld "$@"; fi
echo "ld: not installed. Install with: apt-get install binutils" >&2; exit 1'

_install_shim 'as' '#!/bin/sh
if command -v as >/dev/null 2>&1; then exec as "$@"; fi
echo "as: not installed. Install with: apt-get install binutils" >&2; exit 1'

_install_shim 'cpp' '#!/bin/sh
if command -v cpp >/dev/null 2>&1; then exec cpp "$@"; fi
echo "cpp: not installed. Install with: apt-get install gcc" >&2; exit 1'

_install_shim 'gfortran' '#!/bin/sh
if command -v gfortran >/dev/null 2>&1; then exec gfortran "$@"; fi
echo "gfortran: not installed. Install with: apt-get install gfortran" >&2; exit 1'

_install_shim 'gobjc' '#!/bin/sh
if command -v gobjc >/dev/null 2>&1; then exec gobjc "$@"; fi
echo "gobjc: not installed. Install with: apt-get install gobjc" >&2; exit 1'

# ============================================================
# PACKAGE MANAGEMENT HELPERS
# ============================================================

_install_shim 'pip' '#!/bin/sh
if command -v pip >/dev/null 2>&1; then exec pip "$@"; fi
if command -v pip3 >/dev/null 2>&1; then exec pip3 "$@"; fi
if command -v python3 >/dev/null 2>&1; then
    exec python3 -m pip "$@"
fi
echo "pip: not installed. Install with: apt-get install python3-pip" >&2; exit 1'

_install_shim 'pip3' '#!/bin/sh
if command -v pip3 >/dev/null 2>&1; then exec pip3 "$@"; fi
if command -v python3 >/dev/null 2>&1; then
    exec python3 -m pip "$@"
fi
echo "pip3: not installed. Install with: apt-get install python3-pip" >&2; exit 1'

_install_shim 'python' '#!/bin/sh
if command -v python >/dev/null 2>&1; then exec python "$@"; fi
if command -v python3 >/dev/null 2>&1; then exec python3 "$@"; fi
echo "python: not installed. Install with: apt-get install python3" >&2; exit 1'

_install_shim 'node' '#!/bin/sh
if command -v node >/dev/null 2>&1; then exec node "$@"; fi
echo "node: not installed. Install with: apt-get install nodejs" >&2; exit 1'

_install_shim 'npm' '#!/bin/sh
if command -v npm >/dev/null 2>&1; then exec npm "$@"; fi
echo "npm: not installed. Install with: apt-get install npm" >&2; exit 1'

_install_shim 'npx' '#!/bin/sh
if command -v npx >/dev/null 2>&1; then exec npx "$@"; fi
echo "npx: not installed. Install with: apt-get install npm" >&2; exit 1'

_install_shim 'yarn' '#!/bin/sh
if command -v yarn >/dev/null 2>&1; then exec yarn "$@"; fi
echo "yarn: not installed. Install with: npm install -g yarn" >&2; exit 1'

_install_shim 'pnpm' '#!/bin/sh
if command -v pnpm >/dev/null 2>&1; then exec pnpm "$@"; fi
echo "pnpm: not installed. Install with: npm install -g pnpm" >&2; exit 1'

_install_shim 'cargo' '#!/bin/sh
if command -v cargo >/dev/null 2>&1; then exec cargo "$@"; fi
echo "cargo: not installed. Install with: curl --proto '\''=https'\'' --tlsv1.2 -sSf https://sh.rustup.rs | sh" >&2; exit 1'

_install_shim 'rustc' '#!/bin/sh
if command -v rustc >/dev/null 2>&1; then exec rustc "$@"; fi
echo "rustc: not installed. Install with: curl --proto '\''=https'\'' --tlsv1.2 -sSf https://sh.rustup.rs | sh" >&2; exit 1'

_install_shim 'go' '#!/bin/sh
if command -v go >/dev/null 2>&1; then exec go "$@"; fi
echo "go: not installed. Install with: apt-get install golang-go" >&2; exit 1'

_install_shim 'java' '#!/bin/sh
if command -v java >/dev/null 2>&1; then exec java "$@"; fi
echo "java: not installed. Install with: apt-get install default-jre" >&2; exit 1'

_install_shim 'javac' '#!/bin/sh
if command -v javac >/dev/null 2>&1; then exec javac "$@"; fi
echo "javac: not installed. Install with: apt-get install default-jdk" >&2; exit 1'

# ============================================================
# MEDIA / IMAGE
# ============================================================

_install_shim 'ffmpeg' '#!/bin/sh
if command -v ffmpeg >/dev/null 2>&1; then exec ffmpeg "$@"; fi
echo "ffmpeg: not installed. Install with: apt-get install ffmpeg" >&2; exit 1'

_install_shim 'ffprobe' '#!/bin/sh
if command -v ffprobe >/dev/null 2>&1; then exec ffprobe "$@"; fi
echo "ffprobe: not installed. Install with: apt-get install ffmpeg" >&2; exit 1'

_install_shim 'convert' '#!/bin/sh
if command -v convert >/dev/null 2>&1; then exec convert "$@"; fi
echo "convert: ImageMagick not installed. Install with: apt-get install imagemagick" >&2; exit 1'

_install_shim 'identify' '#!/bin/sh
if command -v identify >/dev/null 2>&1; then exec identify "$@"; fi
echo "identify: ImageMagick not installed. Install with: apt-get install imagemagick" >&2; exit 1'

_install_shim 'montage' '#!/bin/sh
if command -v montage >/dev/null 2>&1; then exec montage "$@"; fi
echo "montage: ImageMagick not installed. Install with: apt-get install imagemagick" >&2; exit 1'

# ============================================================
# TEXT EDITORS
# ============================================================

_install_shim 'emacs' '#!/bin/sh
if command -v emacs >/dev/null 2>&1; then exec emacs "$@"; fi
if command -v nano >/dev/null 2>&1; then echo "emacs not found, falling back to nano"; exec nano "$@"; fi
if command -v vi >/dev/null 2>&1; then echo "emacs not found, falling back to vi"; exec vi "$@"; fi
echo "No text editor available. Install with: apt-get install nano vim emacs" >&2; exit 1'

_install_shim 'vim' '#!/bin/sh
if command -v vim >/dev/null 2>&1; then exec vim "$@"; fi
if command -v vi >/dev/null 2>&1; then exec vi "$@"; fi
if command -v nano >/dev/null 2>&1; then echo "vim not found, falling back to nano"; exec nano "$@"; fi
echo "No text editor available. Install with: apt-get install nano vim" >&2; exit 1'

# ============================================================
# UTILITY / MISC
# ============================================================

_install_shim 'watch' '#!/bin/sh
if command -v watch >/dev/null 2>&1; then exec watch "$@"; fi
interval=2
if [ "$1" = "-n" ]; then shift; interval="$1"; shift; fi
echo "watch: not installed. Install with: apt-get install procps" >&2
echo "Running once instead:"
"$@"'

_install_shim 'screen' '#!/bin/sh
if command -v screen >/dev/null 2>&1; then exec screen "$@"; fi
echo "screen: not installed. Install with: apt-get install screen" >&2; exit 1'

_install_shim 'tmux' '#!/bin/sh
if command -v tmux >/dev/null 2>&1; then exec tmux "$@"; fi
echo "tmux: not installed. Install with: apt-get install tmux" >&2; exit 1'

_install_shim 'byobu' '#!/bin/sh
if command -v byobu >/dev/null 2>&1; then exec byobu "$@"; fi
echo "byobu: not installed. Install with: apt-get install byobu" >&2; exit 1'

_install_shim 'jq' '#!/bin/sh
if command -v jq >/dev/null 2>&1; then exec jq "$@"; fi
# Minimal JSON parser using python3 or awk
if command -v python3 >/dev/null 2>&1; then
    exec python3 -c "import json,sys; d=json.load(sys.stdin); print(json.dumps(d, indent=2))" "$@"
fi
echo "jq: not installed. Install with: apt-get install jq" >&2; exit 1'

_install_shim 'yq' '#!/bin/sh
if command -v yq >/dev/null 2>&1; then exec yq "$@"; fi
echo "yq: not installed. Install with: apt-get install yq" >&2; exit 1'

_install_shim 'xmlstarlet' '#!/bin/sh
if command -v xmlstarlet >/dev/null 2>&1; then exec xmlstarlet "$@"; fi
echo "xmlstarlet: not installed. Install with: apt-get install xmlstarlet" >&2; exit 1'

_install_shim 'xsel' '#!/bin/sh
if command -v xsel >/dev/null 2>&1; then exec xsel "$@"; fi
echo "xsel: not available in proot" >&2; exit 1'

_install_shim 'xclip' '#!/bin/sh
if command -v xclip >/dev/null 2>&1; then exec xclip "$@"; fi
echo "xclip: not available in proot" >&2; exit 1'

_install_shim 'pbcopy' '#!/bin/sh
if command -v pbcopy >/dev/null 2>&1; then exec pbcopy "$@"; fi
cat > /tmp/.quro_clipboard
echo "Copied to clipboard (local)"'

_install_shim 'pbpaste' '#!/bin/sh
if command -v pbpaste >/dev/null 2>&1; then exec pbpaste "$@"; fi
cat /tmp/.quro_clipboard 2>/dev/null || echo "Clipboard empty"'

_install_shim 'notify-send' '#!/bin/sh
if command -v notify-send >/dev/null 2>&1; then exec notify-send "$@"; fi
echo "Notification: $*"' 2>/dev/null || true

_install_shim 'xdg-open' '#!/bin/sh
if command -v xdg-open >/dev/null 2>&1; then exec xdg-open "$@"; fi
echo "xdg-open: not available in proot" >&2; exit 1'

_install_shim 'open' '#!/bin/sh
if command -v open >/dev/null 2>&1; then exec open "$@"; fi
echo "open: not available in proot. Use xdg-open instead." >&2; exit 1'

_install_shim 'say' '#!/bin/sh
if command -v say >/dev/null 2>&1; then exec say "$@"; fi
# Try espeak or festival
if command -v espeak >/dev/null 2>&1; then exec espeak "$@"; fi
if command -v festival >/dev/null 2>&1; then echo "$*" | festival --tts; exit 0; fi
echo "say: no TTS engine available. Install with: apt-get install espeak" >&2; exit 1'

_install_shim 'espeak' '#!/bin/sh
if command -v espeak >/dev/null 2>&1; then exec espeak "$@"; fi
echo "espeak: not installed. Install with: apt-get install espeak" >&2; exit 1'

_install_shim 'figlet' '#!/bin/sh
if command -v figlet >/dev/null 2>&1; then exec figlet "$@"; fi
echo "figlet: not installed. Install with: apt-get install figlet" >&2; exit 1'

_install_shim 'cowsay' '#!/bin/sh
if command -v cowsay >/dev/null 2>&1; then exec cowsay "$@"; fi
# Minimal cowsay
msg="${*:-Moo!}"
len=${#msg}
echo " ___________"
echo "< $msg >"
echo " -----------"
echo "        \\   ^__^"
echo "         \\  (oo)\\_______"
echo "            (__)\\       )\\/\\"
echo "                ||----w |"
echo "                ||     ||"'

_install_shim 'cal' '#!/bin/sh
if command -v cal >/dev/null 2>&1; then exec cal "$@"; fi
# Minimal calendar
cal 2>/dev/null || python3 -c "import calendar; calendar.prmonth()" 2>/dev/null || echo "cal: not available"'

_install_shim 'factor' '#!/bin/sh
if command -v factor >/dev/null 2>&1; then exec factor "$@"; fi
# Minimal factor
n="$1"
if [ -z "$n" ]; then echo "Usage: factor <number>" >&2; exit 1; fi
echo -n "$n: "
i=2
while [ $i -le $n ]; do
    while [ $((n % i)) -eq 0 ]; do
        echo -n "$i "
        n=$((n / i))
    done
    i=$((i + 1))
done
echo'

_install_shim 'seq' '#!/bin/sh
if command -v seq >/dev/null 2>&1; then exec seq "$@"; fi
# Minimal seq
case $# in
    1) i=1; e=$1; s=1 ;;
    2) i=$1; e=$2; s=1 ;;
    3) i=$1; s=$2; e=$3 ;;
    *) echo "Usage: seq [FIRST] [INCREMENT] LAST" >&2; exit 1 ;;
esac
while [ $i -le $e ]; do echo $i; i=$((i + s)); done'

_install_shim 'shuf' '#!/bin/sh
if command -v shuf >/dev/null 2>&1; then exec shuf "$@"; fi
# Minimal shuf using awk
awk 'BEGIN{srand()} {print rand(), \$0}' "$@" | sort -n | cut -d" " -f2-'

_install_shim 'numfmt' '#!/bin/sh
if command -v numfmt >/dev/null 2>&1; then exec numfmt "$@"; fi
echo "numfmt: not installed. Install with: apt-get install coreutils" >&2; exit 1'

_install_shim 'base32' '#!/bin/sh
if command -v base32 >/dev/null 2>&1; then exec base32 "$@"; fi
# Use python3 for base32
if command -v python3 >/dev/null 2>&1; then
    exec python3 -c "import sys,base64; sys.stdout.buffer.write(base64.b32encode(sys.stdin.buffer.read()))" "$@"
fi
echo "base32: not available" >&2; exit 1'

_install_shim 'base64' '#!/bin/sh
if command -v base64 >/dev/null 2>&1; then exec base64 "$@"; fi
# Use python3 for base64
if command -v python3 >/dev/null 2>&1; then
    case "$1" in
        -d|--decode)
            shift
            exec python3 -c "import sys,base64; sys.stdout.buffer.write(base64.b64decode(sys.stdin.buffer.read()))" "$@"
            ;;
        *)
            exec python3 -c "import sys,base64; sys.stdout.buffer.write(base64.b64encode(sys.stdin.buffer.read()))" "$@"
            ;;
    esac
fi
echo "base64: not available" >&2; exit 1'

_install_shim 'chroot' '#!/bin/sh
if command -v chroot >/dev/null 2>&1; then exec chroot "$@"; fi
echo "chroot: not available in proot (you are already in a proot environment)" >&2; exit 1'

_install_shim 'pivot_root' '#!/bin/sh
echo "pivot_root: not available in proot" >&2; exit 1'

_install_shim 'unshare' '#!/bin/sh
if command -v unshare >/dev/null 2>&1; then exec unshare "$@"; fi
echo "unshare: not available in proot" >&2; exit 1'

_install_shim 'nsenter' '#!/bin/sh
if command -v nsenter >/dev/null 2>&1; then exec nsenter "$@"; fi
echo "nsenter: not available in proot" >&2; exit 1'

_install_shim 'chrt' '#!/bin/sh
if command -v chrt >/dev/null 2>&1; then exec chrt "$@"; fi
echo "chrt: not available in proot" >&2; exit 1'

_install_shim 'taskset' '#!/bin/sh
if command -v taskset >/dev/null 2>&1; then exec taskset "$@"; fi
echo "taskset: not available in proot" >&2; exit 1'

_install_shim 'ionice' '#!/bin/sh
if command -v ionice >/dev/null 2>&1; then exec ionice "$@"; fi
echo "ionice: not available in proot" >&2; exit 1'

_install_shim 'setsid' '#!/bin/sh
if command -v setsid >/dev/null 2>&1; then exec setsid "$@"; fi
"$@"'

_install_shim 'script' '#!/bin/sh
if command -v script >/dev/null 2>&1; then exec script "$@"; fi
echo "script: not available in proot" >&2
exec "$@"'

_install_shim 'wall' '#!/bin/sh
if command -v wall >/dev/null 2>&1; then exec wall "$@"; fi
echo "wall: not available in proot" >&2; exit 1'

_install_shim 'mesg' '#!/bin/sh
if command -v mesg >/dev/null 2>&1; then exec mesg "$@"; fi
echo "y"'

_install_shim 'write' '#!/bin/sh
if command -v write >/dev/null 2>&1; then exec write "$@"; fi
echo "write: not available in proot" >&2; exit 1'

_install_shim 'cru' '#!/bin/sh
if command -v cru >/dev/null 2>&1; then exec cru "$@"; fi
echo "cru: cron not available in proot. Use 'at' or background processes instead." >&2; exit 1'

_install_shim 'crontab' '#!/bin/sh
if command -v crontab >/dev/null 2>&1; then exec crontab "$@"; fi
echo "crontab: cron not available in proot. Use 'at' or background processes instead." >&2; exit 1'

_install_shim 'at' '#!/bin/sh
if command -v at >/dev/null 2>&1; then exec at "$@"; fi
echo "at: not installed. Install with: apt-get install at" >&2; exit 1'

_install_shim 'batch' '#!/bin/sh
if command -v batch >/dev/null 2>&1; then exec batch "$@"; fi
echo "batch: not installed. Install with: apt-get install at" >&2; exit 1'

_install_shim 'dpkg-deb' '#!/bin/sh
if command -v dpkg-deb >/dev/null 2>&1; then exec dpkg-deb "$@"; fi
echo "dpkg-deb: not installed. Install with: apt-get install dpkg" >&2; exit 1'

_install_shim 'dpkg-query' '#!/bin/sh
if command -v dpkg-query >/dev/null 2>&1; then exec dpkg-query "$@"; fi
echo "dpkg-query: not installed. Install with: apt-get install dpkg" >&2; exit 1'

_install_shim 'apt-cache' '#!/bin/sh
if command -v apt-cache >/dev/null 2>&1; then exec apt-cache "$@"; fi
echo "apt-cache: not installed. Install with: apt-get install apt" >&2; exit 1'

_install_shim 'apt-config' '#!/bin/sh
if command -v apt-config >/dev/null 2>&1; then exec apt-config "$@"; fi
echo "apt-config: not installed. Install with: apt-get install apt" >&2; exit 1'

_install_shim 'apt-mark' '#!/bin/sh
if command -v apt-mark >/dev/null 2>&1; then exec apt-mark "$@"; fi
echo "apt-mark: not installed. Install with: apt-get install apt" >&2; exit 1'

_install_shim 'apt-sortpackages' '#!/bin/sh
if command -v apt-sortpackages >/dev/null 2>&1; then exec apt-sortpackages "$@"; fi
echo "apt-sortpackages: not installed" >&2; exit 1'

_install_shim 'apt-extracttemplates' '#!/bin/sh
if command -v apt-extracttemplates >/dev/null 2>&1; then exec apt-extracttemplates "$@"; fi
echo "apt-extracttemplates: not installed" >&2; exit 1'

# Count installed shims
echo "[quro-commands] Installed $(ls -1 "$SHIM_DIR" 2>/dev/null | wc -l) commands in $SHIM_DIR"

# ============================================================
# SHELL COMPATIBILITY LAYER
# ============================================================

# Ensure /bin/sh exists and works
if [ ! -x /bin/sh ] && [ -x /usr/bin/sh ]; then
    ln -sf /usr/bin/sh /bin/sh 2>/dev/null || true
fi

# Ensure common shell config files exist
for f in /etc/profile /etc/bash.bashrc /etc/environment; do
    if [ ! -f "$f" ]; then
        touch "$f" 2>/dev/null || true
    fi
done

# Create /etc/shells if missing (needed for chsh)
if [ ! -f /etc/shells ]; then
    cat > /etc/shells 2>/dev/null << 'SHELLS'
/bin/sh
/bin/bash
/usr/bin/sh
/usr/bin/bash
SHELLS
fi

# Ensure /tmp exists with proper permissions
chmod 1777 /tmp 2>/dev/null || true

echo "[quro-commands] Shell compatibility layer installed"
